//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rocketnote.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rocketnote.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string AppBarCancel {
            get {
                return ResourceManager.GetString("AppBarCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empty trash.
        /// </summary>
        public static string AppBarEmptyBar {
            get {
                return ResourceManager.GetString("AppBarEmptyBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guide.
        /// </summary>
        public static string AppBarGuide {
            get {
                return ResourceManager.GetString("AppBarGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new note.
        /// </summary>
        public static string AppBarNewNote {
            get {
                return ResourceManager.GetString("AppBarNewNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string AppBarSave {
            get {
                return ResourceManager.GetString("AppBarSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string AppBarSettings {
            get {
                return ResourceManager.GetString("AppBarSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sort notes.
        /// </summary>
        public static string AppBarSortNotes {
            get {
                return ResourceManager.GetString("AppBarSortNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to synchronize.
        /// </summary>
        public static string AppBarSynchronize {
            get {
                return ResourceManager.GetString("AppBarSynchronize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rocketnote+.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete notes from a notebook or move to trash to add new.
        /// </summary>
        public static string MsgIfAddNewNote {
            get {
                return ResourceManager.GetString("MsgIfAddNewNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notebook is full.
        /// </summary>
        public static string MsgNotebookIsFull {
            get {
                return ResourceManager.GetString("MsgNotebookIsFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new note.
        /// </summary>
        public static string PageNewNote {
            get {
                return ResourceManager.GetString("PageNewNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sort notes.
        /// </summary>
        public static string PageSortNotes {
            get {
                return ResourceManager.GetString("PageSortNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new note.
        /// </summary>
        public static string PageTitleNewNote {
            get {
                return ResourceManager.GetString("PageTitleNewNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to options.
        /// </summary>
        public static string PageTitleNewNoteOptions {
            get {
                return ResourceManager.GetString("PageTitleNewNoteOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notebook.
        /// </summary>
        public static string PageTitleNotebook {
            get {
                return ResourceManager.GetString("PageTitleNotebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trash.
        /// </summary>
        public static string PageTitleTrash {
            get {
                return ResourceManager.GetString("PageTitleTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to note.
        /// </summary>
        public static string PageTitleViewNote {
            get {
                return ResourceManager.GetString("PageTitleViewNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Runtime Property Value.
        /// </summary>
        public static string SampleProperty {
            get {
                return ResourceManager.GetString("SampleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no category.
        /// </summary>
        public static string TextCategory0 {
            get {
                return ResourceManager.GetString("TextCategory0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hobby.
        /// </summary>
        public static string TextCategory1 {
            get {
                return ResourceManager.GetString("TextCategory1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to home.
        /// </summary>
        public static string TextCategory2 {
            get {
                return ResourceManager.GetString("TextCategory2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to work.
        /// </summary>
        public static string TextCategory3 {
            get {
                return ResourceManager.GetString("TextCategory3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shopping.
        /// </summary>
        public static string TextCategory4 {
            get {
                return ResourceManager.GetString("TextCategory4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to science.
        /// </summary>
        public static string TextCategory5 {
            get {
                return ResourceManager.GetString("TextCategory5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other.
        /// </summary>
        public static string TextCategory6 {
            get {
                return ResourceManager.GetString("TextCategory6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string TextNote {
            get {
                return ResourceManager.GetString("TextNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TextTitle {
            get {
                return ResourceManager.GetString("TextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type a note.
        /// </summary>
        public static string TextTypeNote {
            get {
                return ResourceManager.GetString("TextTypeNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type a title.
        /// </summary>
        public static string TextTypeTitle {
            get {
                return ResourceManager.GetString("TextTypeTitle", resourceCulture);
            }
        }
    }
}
