//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rocketnote.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rocketnote.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AppBarAbout {
            get {
                return ResourceManager.GetString("AppBarAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string AppBarCancel {
            get {
                return ResourceManager.GetString("AppBarCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string AppBarEdit {
            get {
                return ResourceManager.GetString("AppBarEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empty trash.
        /// </summary>
        public static string AppBarEmptyTrash {
            get {
                return ResourceManager.GetString("AppBarEmptyTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to like me.
        /// </summary>
        public static string AppBarLikeMe {
            get {
                return ResourceManager.GetString("AppBarLikeMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to move to Trash.
        /// </summary>
        public static string AppBarMoveToTrash {
            get {
                return ResourceManager.GetString("AppBarMoveToTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new note.
        /// </summary>
        public static string AppBarNewNote {
            get {
                return ResourceManager.GetString("AppBarNewNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin.
        /// </summary>
        public static string AppBarPin {
            get {
                return ResourceManager.GetString("AppBarPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate me.
        /// </summary>
        public static string AppBarRateMe {
            get {
                return ResourceManager.GetString("AppBarRateMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string AppBarSave {
            get {
                return ResourceManager.GetString("AppBarSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string AppBarSettings {
            get {
                return ResourceManager.GetString("AppBarSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share.
        /// </summary>
        public static string AppBarShareNote {
            get {
                return ResourceManager.GetString("AppBarShareNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sort notes.
        /// </summary>
        public static string AppBarSortNotes {
            get {
                return ResourceManager.GetString("AppBarSortNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to store.
        /// </summary>
        public static string AppBarStore {
            get {
                return ResourceManager.GetString("AppBarStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unpin.
        /// </summary>
        public static string AppBarUnpin {
            get {
                return ResourceManager.GetString("AppBarUnpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROCKETNOTE.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROCKETNOTE.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all notes.
        /// </summary>
        public static string ButtonResetNotesList {
            get {
                return ResourceManager.GetString("ButtonResetNotesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Tu wpisz swoje uwagi]
        ///
        ///
        ///---------------------------------
        ///Device Name: {0}
        ///Device Manufacturer: {1}
        ///Device Firmware Version: {2}
        ///Device Hardware Version: {3}
        ///Application Version: {4}
        ///---------------------------------.
        /// </summary>
        public static string FeedbackBody {
            get {
                return ResourceManager.GetString("FeedbackBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry to hear you didn&apos;t want to rate Rocketnote.
        ///
        ///Tell us about your experience or suggest how we can make it even better..
        /// </summary>
        public static string FeedbackMessage1 {
            get {
                return ResourceManager.GetString("FeedbackMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no thanks.
        /// </summary>
        public static string FeedbackNo {
            get {
                return ResourceManager.GetString("FeedbackNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rocketnote Customer Feedback.
        /// </summary>
        public static string FeedbackSubject {
            get {
                return ResourceManager.GetString("FeedbackSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can we make it better?.
        /// </summary>
        public static string FeedbackTitle {
            get {
                return ResourceManager.GetString("FeedbackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mobileapps@aturex.pl.
        /// </summary>
        public static string FeedbackTo {
            get {
                return ResourceManager.GetString("FeedbackTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to give feedback.
        /// </summary>
        public static string FeedbackYes {
            get {
                return ResourceManager.GetString("FeedbackYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for choosing Rocketnote. 
        ///Rocketnote is a small, fast and secure notebook. It provides the following fuctions: add, edit, sort and delete notes. Your notes are available only on the phone so that no one can access them.
        ///I hope that you&apos;ll be doing Rocketnote in daily work..
        /// </summary>
        public static string FirstNoteContent {
            get {
                return ResourceManager.GetString("FirstNoteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string FirstNoteTitle {
            get {
                return ResourceManager.GetString("FirstNoteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to move to notepad.
        /// </summary>
        public static string MenuMoveToNotebook {
            get {
                return ResourceManager.GetString("MenuMoveToNotebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to move to trash.
        /// </summary>
        public static string MenuMoveToTrash {
            get {
                return ResourceManager.GetString("MenuMoveToTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share.
        /// </summary>
        public static string MenuShareNote {
            get {
                return ResourceManager.GetString("MenuShareNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All notes will be deleted from the phone.
        /// </summary>
        public static string MsgAllNotesDeleted {
            get {
                return ResourceManager.GetString("MsgAllNotesDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all notes?.
        /// </summary>
        public static string MsgDeleteAllNotes {
            get {
                return ResourceManager.GetString("MsgDeleteAllNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the oldest notes?.
        /// </summary>
        public static string MsgDeleteOldestNotes {
            get {
                return ResourceManager.GetString("MsgDeleteOldestNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete notes from notebook or move to trash to change the value.
        /// </summary>
        public static string MsgDeleteOrMoveNote {
            get {
                return ResourceManager.GetString("MsgDeleteOrMoveNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete notes from a notebook or move to trash to add new.
        /// </summary>
        public static string MsgIfAddNewNote {
            get {
                return ResourceManager.GetString("MsgIfAddNewNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notebook is full.
        /// </summary>
        public static string MsgNotebookIsFull {
            get {
                return ResourceManager.GetString("MsgNotebookIsFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash is full.
        /// </summary>
        public static string MsgTrashIsFull {
            get {
                return ResourceManager.GetString("MsgTrashIsFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT.
        /// </summary>
        public static string PageTitleAbout {
            get {
                return ResourceManager.GetString("PageTitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT NOTE.
        /// </summary>
        public static string PageTitleEditNote {
            get {
                return ResourceManager.GetString("PageTitleEditNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW NOTE.
        /// </summary>
        public static string PageTitleNewNote {
            get {
                return ResourceManager.GetString("PageTitleNewNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE.
        /// </summary>
        public static string PageTitleNote {
            get {
                return ResourceManager.GetString("PageTitleNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notebook.
        /// </summary>
        public static string PageTitleNotebook {
            get {
                return ResourceManager.GetString("PageTitleNotebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string PageTitleSettings {
            get {
                return ResourceManager.GetString("PageTitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHARE NOTE.
        /// </summary>
        public static string PageTitleShare {
            get {
                return ResourceManager.GetString("PageTitleShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SORT NOTES.
        /// </summary>
        public static string PageTitleSort {
            get {
                return ResourceManager.GetString("PageTitleSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trash.
        /// </summary>
        public static string PageTitleTrash {
            get {
                return ResourceManager.GetString("PageTitleTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;d love you to rate our app 5 stars
        ///
        ///Showing us some love on the store helps us to continue to work on the app and make things even better!.
        /// </summary>
        public static string RatingMessage1 {
            get {
                return ResourceManager.GetString("RatingMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You look to be getting a lot of use out of our application!
        ///
        ///Why not give us a 5 star rating to show your appreciation?.
        /// </summary>
        public static string RatingMessage2 {
            get {
                return ResourceManager.GetString("RatingMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no thanks.
        /// </summary>
        public static string RatingNo {
            get {
                return ResourceManager.GetString("RatingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoying Rocketnote?.
        /// </summary>
        public static string RatingTitle {
            get {
                return ResourceManager.GetString("RatingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate 5 stars.
        /// </summary>
        public static string RatingYes {
            get {
                return ResourceManager.GetString("RatingYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to author.
        /// </summary>
        public static string TextAuthor {
            get {
                return ResourceManager.GetString("TextAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change theme.
        /// </summary>
        public static string TextChangeTheme {
            get {
                return ResourceManager.GetString("TextChangeTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning.
        /// </summary>
        public static string TextCleaning {
            get {
                return ResourceManager.GetString("TextCleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note created by Rocketnote for Windows Phone.
        /// </summary>
        public static string TextCreatedBy {
            get {
                return ResourceManager.GetString("TextCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dark.
        /// </summary>
        public static string TextDarkTheme {
            get {
                return ResourceManager.GetString("TextDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can delete all notes from the note list and trash..
        /// </summary>
        public static string TextDeleteAllNotes {
            get {
                return ResourceManager.GetString("TextDeleteAllNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete notes.
        /// </summary>
        public static string TextDeleteNotes {
            get {
                return ResourceManager.GetString("TextDeleteNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.
        /// </summary>
        public static string TextEmail {
            get {
                return ResourceManager.GetString("TextEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I like Rocketnote.
        /// </summary>
        public static string TextEmailSubiect {
            get {
                return ResourceManager.GetString("TextEmailSubiect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to news :: tips :: information.
        /// </summary>
        public static string TextFacebookContent {
            get {
                return ResourceManager.GetString("TextFacebookContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TextFacebookInfo {
            get {
                return ResourceManager.GetString("TextFacebookInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rocketnote on Facebook.
        /// </summary>
        public static string TextFacebookTitle {
            get {
                return ResourceManager.GetString("TextFacebookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you exceed the size, the oldest note will be permanently deleted.
        /// </summary>
        public static string TextIfTrashIsFull {
            get {
                return ResourceManager.GetString("TextIfTrashIsFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rocketnote is a small, fast and simple notebook.
        ///It provides the following fuctions:
        /// • add note
        /// • edit note
        /// • sort notes
        /// • move note to trash
        /// • delete note
        /// • share note via SMS, Email, Social Network
        /// • pinning notes to the start screen.
        /// </summary>
        public static string TextInfo {
            get {
                return ResourceManager.GetString("TextInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to light.
        /// </summary>
        public static string TextLightTheme {
            get {
                return ResourceManager.GetString("TextLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string TextNote {
            get {
                return ResourceManager.GetString("TextNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notebook.
        /// </summary>
        public static string TextNotebook {
            get {
                return ResourceManager.GetString("TextNotebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notebook size.
        /// </summary>
        public static string TextNotebookSize {
            get {
                return ResourceManager.GetString("TextNotebookSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organize notes in notebook.
        /// </summary>
        public static string TextOrganizeNotes {
            get {
                return ResourceManager.GetString("TextOrganizeNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string TextPriority {
            get {
                return ResourceManager.GetString("TextPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to high.
        /// </summary>
        public static string TextPriorityHigh {
            get {
                return ResourceManager.GetString("TextPriorityHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to normal.
        /// </summary>
        public static string TextPriorityNormal {
            get {
                return ResourceManager.GetString("TextPriorityNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the maximum number of notes in a notebook.
        /// </summary>
        public static string TextSetMaxInNotebook {
            get {
                return ResourceManager.GetString("TextSetMaxInNotebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the maximum number of notes in trash.
        /// </summary>
        public static string TextSetMaxInTrash {
            get {
                return ResourceManager.GetString("TextSetMaxInTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share via E-mail.
        /// </summary>
        public static string TextShareEmail {
            get {
                return ResourceManager.GetString("TextShareEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share via SMS.
        /// </summary>
        public static string TextShareSms {
            get {
                return ResourceManager.GetString("TextShareSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share your status to social network.
        /// </summary>
        public static string TextShareSocialNetwork {
            get {
                return ResourceManager.GetString("TextShareSocialNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sort alphabetically.
        /// </summary>
        public static string TextSortAlphabetically {
            get {
                return ResourceManager.GetString("TextSortAlphabetically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sort by category.
        /// </summary>
        public static string TextSortByCategory {
            get {
                return ResourceManager.GetString("TextSortByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sort by change date.
        /// </summary>
        public static string TextSortByChangeDate {
            get {
                return ResourceManager.GetString("TextSortByChangeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sort by creation date.
        /// </summary>
        public static string TextSortByCreationDate {
            get {
                return ResourceManager.GetString("TextSortByCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting.
        /// </summary>
        public static string TextSorting {
            get {
                return ResourceManager.GetString("TextSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string TextTheme {
            get {
                return ResourceManager.GetString("TextTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart to apply the theme change.
        /// </summary>
        public static string TextThemeMessage {
            get {
                return ResourceManager.GetString("TextThemeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TextTitle {
            get {
                return ResourceManager.GetString("TextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash.
        /// </summary>
        public static string TextTrash {
            get {
                return ResourceManager.GetString("TextTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash size.
        /// </summary>
        public static string TextTrashSize {
            get {
                return ResourceManager.GetString("TextTrashSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type a note.
        /// </summary>
        public static string TextTypeNote {
            get {
                return ResourceManager.GetString("TextTypeNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type a title.
        /// </summary>
        public static string TextTypeTitle {
            get {
                return ResourceManager.GetString("TextTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version.
        /// </summary>
        public static string TextVersion {
            get {
                return ResourceManager.GetString("TextVersion", resourceCulture);
            }
        }
    }
}
